Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,16 +1,49 @@
-name: release
+name: SemVer Release Workflow
 
+run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"
+
+# Trigger workflow manually
 on:
-  workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      release_version:
+        type: string
+        description: "(Optional) Custom Release Version"
+        required: false
+      version_type:
+        description: 'Development version type to increment'
+        required: true
+        default: 'minor'
+        type: choice
+        options:
+          - major
+          - minor
+          - patch
+
+env:
+  BRANCH_NAME: ${{ github.ref_name }}
+  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}
 
 jobs:
   release:
-    runs-on: ubuntu-latest
+    name: Release
+    runs-on: ubuntu-24.04
+    if: github.repository_owner == 'ikmdev'
     steps:
-      - uses: eitco/maven-release@0.0.1
+      - name: Verify Branch
+        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
+        run: |
+          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only."
+          exit 1
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
         with:
-          gpg-private-key: ${{ secrets.ARTIFACT_SIGNING_GPG_PRIVATE_KEY }}
-          gpg-key-name: ${{ secrets.ARTIFACT_SIGNING_GPG_KEY_NAME }}
-          gpg-passphrase: ${{ secrets.ARTIFACT_SIGNING_GPG_PRIVATE_KEY_PASSWORD }}
-          deploy-user: ${{ secrets.OSSRH_JIRA_USERNAME }}
-          deploy-password: ${{ secrets.OSSRH_JIRA_PASSWORD }}
+          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
+
+      - name: Shared Release Action
+        uses: ikmdev/maven-semver-release-action@v2
+        with:
+          version_type: ${{ github.event.inputs.version_type }}
+          github_token: ${{secrets.GITHUB_TOKEN}}
+          release_version: ${{ github.event.inputs.release_version }}
